### ISSUE TITLE
Default horizontal lines are not recognized

### ISSUE THREAD

**Issue by KaratasFurkan** [casouri/ftable#1]
Hello, thanks for your package, this was a feature a was looking for.

When I create a table with default horizontal lines like `|----+-----+----|` your `ftable--table-info` return `tablep = nil`. Editing horizontal lines like in your readme `+----+-----+----+` solves the problem but I need to edit them manually every time.

Setting `ftable-box-charset-alist` variable will solve this issue probably but I wanted to open this PR to know why you use custom hlines. Is there any way to change how org inserts hlines?

**Comment by casouri** [comment]
Maybe I should say it in the readme, this package is for table.el tables. I thought `|----+-----+----|` is only for Org Mode's single line tables? I.e., 
```
| Head 1 | Head 2 |
|--------+--------|
| Cell 1 | Cell 2 |
| Cell 3 | Cell 4 |
```

[table.el table](https://www.gnu.org/software/emacs/manual/html_node/emacs/Text-Based-Tables.html)

(Of course, I would be lying to say ftable fully supports table.el tables because table.el tables can have compound cells which ftable doesn't support)

**Comment by KaratasFurkan** [comment]
I see. I forgot about table.el, thank you.
